package enumeration;

public enum Degree {
    COLLAGE,
    BACHELOR_CONNECTED,
    BACHELOR_NOT_CONNECTED,
    MASTERS_CONNECTED,
    MASTERS_NOT_CONNECTED,
    PROFESSIONAL_PHD,
    PHD_CONNECTED,
    PHD_NOT_CONNECTED
}
